#site_name: "Documentation"
site_name: leetcode python solutions
site_author: Yunusov Abdulmajid
site_description: notion-mkdocs is a Python package that allows you to convert Notion pages into Markdown files and then build a static site using MkDocs. This tool streamlines the process of turning your Notion content into a well-structured, easily navigable documentation site.
site_url: https://under-script.github.io/leetcode-solutions/
copyright: "Â© 2024 Notion mkdocs"
repo_name: under-script/leetcode-solutions
repo_url: https://github.com/under-script/leetcode-solutions

theme:
  name: material
  favicon: "./img/favicon.ico"
  logo: "./img/favicon.png"
  palette:
    scheme: slate
    primary: 'black'
    accent: 'yellow'
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Tahoma
    code: Source Code Pro

plugins:
  - search
social:
  - icon: fontawesome/brands/github
    link: https://github.com/under-script/leetcode-solutions
